#!/usr/bin/env python3
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parents[3]
MANIFEST_PATH = ROOT / "MANIFEST.json"
INDEX_PATH = ROOT / "INDEX.md"

REQUIRED_FILES = [
    "baseline.json",
    "timeline.jsonl",
    "decision_records.jsonl",
    "containment_metrics.json",
    "system_state.txt",
    "EVIDENCE_INDEX.md",
]

def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def get_field(obj, dotted):
    cur = obj
    for part in dotted.split('.'):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur

def ensure(cond: bool, msg: str):
    if not cond:
        raise RuntimeError(msg)

def verify_run(run: dict):
    run_dir = ROOT / run["bundle_run_dir"]
    ensure(run_dir.is_dir(), f"missing run dir: {run_dir}")

    for f in REQUIRED_FILES:
        ensure((run_dir / f).exists(), f"missing required file {f} in {run['id']}")

    dec_path = run_dir / "decision_records.jsonl"
    decision_sha = sha256_file(dec_path)
    ensure(decision_sha == run["decision_records_sha256"], f"decision sha mismatch in {run['id']}")

    lines = [x for x in dec_path.read_text(encoding="utf-8").splitlines() if x.strip()]
    ensure(lines, f"empty decision_records in {run['id']}")
    decision = json.loads(lines[-1])

    req_path = REPO_ROOT / run["required_fields_ref"]
    required_fields = json.loads(req_path.read_text(encoding="utf-8"))["required_fields"]
    for field in required_fields:
        v = get_field(decision, field)
        ensure(v is not None, f"missing required field {field} in {run['id']}")

    baseline_contract = REPO_ROOT / run["baseline_contract_ref"]
    baseline_hash = sha256_file(baseline_contract)
    ensure(
        decision["decision"]["baseline_hash"] == baseline_hash,
        f"baseline hash mismatch (decision) in {run['id']}",
    )

    receipt = json.loads((run_dir / "baseline.json").read_text(encoding="utf-8"))
    ensure(
        receipt.get("baseline_hash") == baseline_hash,
        f"baseline hash mismatch (receipt) in {run['id']}",
    )

    ensure(decision["decision"]["outcome"] == run["expected"]["outcome"], f"outcome mismatch in {run['id']}")
    ensure(
        decision["decision"]["reason_code"] in run["expected"]["reason_codes"],
        f"reason_code mismatch in {run['id']}",
    )

    metrics = decision.get("metrics", {})
    if run["domain_pack_id"].startswith("D1-digital"):
        ensure(metrics.get("connect_established") is False, f"D1 connect_established must be false in {run['id']}")
        ensure(metrics.get("bytes_exfiltrated") == 0, f"D1 bytes_exfiltrated must be 0 in {run['id']}")
    if run["domain_pack_id"].startswith("D8-scientific"):
        ensure(metrics.get("outputs_persisted") is False, f"D8 outputs_persisted must be false in {run['id']}")
        ensure(metrics.get("bytes_written") == 0, f"D8 bytes_written must be 0 in {run['id']}")
        ensure(metrics.get("artifacts_delta") == 0, f"D8 artifacts_delta must be 0 in {run['id']}")

    return {
        "id": run["id"],
        "pack": run["domain_pack_id"],
        "outcome": decision["decision"]["outcome"],
        "reason": decision["decision"]["reason_code"],
        "baseline_hash": decision["decision"]["baseline_hash"],
        "target_reachable": metrics.get("target_reachable"),
        "connect_established": metrics.get("connect_established", "n/a"),
        "bytes_exfiltrated": metrics.get("bytes_exfiltrated", "n/a"),
        "outputs_persisted": metrics.get("outputs_persisted", "n/a"),
        "bytes_written": metrics.get("bytes_written", "n/a"),
        "artifacts_delta": metrics.get("artifacts_delta", "n/a"),
    }

def write_index(rows):
    lines = []
    lines.append("# Wave 1 Evidence Index")
    lines.append("")
    lines.append("| Pack | Run | Outcome | Reason | Baseline Hash | target_reachable | connect_established | bytes_exfiltrated | outputs_persisted | bytes_written | artifacts_delta |")
    lines.append("|---|---|---|---|---|---:|---:|---:|---:|---:|---:|")
    for r in rows:
        lines.append(
            f"| `{r['pack']}` | `{r['id']}` | `{r['outcome']}` | `{r['reason']}` | `{r['baseline_hash']}` | {r['target_reachable']} | {r['connect_established']} | {r['bytes_exfiltrated']} | {r['outputs_persisted']} | {r['bytes_written']} | {r['artifacts_delta']} |"
        )
    lines.append("")
    lines.append("Generated by `verify/verify_wave1.py`.")
    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    rows = [verify_run(run) for run in manifest["runs"]]
    write_index(rows)
    print("PASS: Wave 1 bundle verified")

if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        sys.exit(1)
